name: Deploy the static file to GitHub Page
on: [push]
jobs:

  build:
  
    name: Build
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.1
      with: 
        node-version: 12.x
    - run: npm cli
    
    - run: npm run build --if-present
    
    - run: npm test
    - name: Deploy to GitHub Pages
  # You may pin to the exact commit or the version.
  # uses: JamesIves/github-pages-deploy-action@89911566f979b4e138ac82c96c9b2aa7ea97759b
      uses: JamesIves/github-pages-deploy-action@4.2.0
      with:

       branch: main
    # The folder in your repository that you want to deploy. If your build script compiles into a directory named build you would put it here. Folder paths cannot have a leading / or ./. If you wish to deploy the root directory you can place a . here.
       folder: public
   
