name: Deploy the static file to GitHub Page
on: [push]
jobs:

  build:
  
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: GitHub Pages Deploy
      uses: appleboy/gh-pages-action@v0.0.2

    - name: checkout
      uses: actions/checkout@v1

    - name: deploy docs
      uses: ./
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        remote_url: https://github.com/Gilles98/gh-pages-action.git
