name: Deploy the static file to GitHub Page
on: [push]
jobs:

  build:
  
    name: Build
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
      
    - name: Setup Node.js environment & deploy
      uses: actions/setup-node@v2.5.1
      with: 
        node-version: 12.x
        cache: 'npm'

    - run: npm build
    
    - run: npm run deploy
   
